project:
  type: book
  output-dir: docs

book:
  title: "R-Universe Docs"
  reader-mode: true
  site-url: https://docs.r-universe.dev/
  repo-url: https://github.com/r-universe-org/hitchhikers-guide
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - part: Browse
      chapters:
        - browse/get-started.qmd
        - browse/search.qmd
        - browse/universes.qmd
        - browse/packages.qmd
        - browse/api.qmd
        - browse/rss-feeds.qmd
    - part: Install
      chapters:
        - install/binaries.qmd
        - install/reproducibility.qmd
    - part: Publish
      chapters:
        - publish/get-started.qmd
        - publish/set-up.qmd
        - publish/metadata.qmd
        - publish/troubleshoot-build.qmd
        - publish/terms.qmd
        - publish/other-networks.qmd
lightbox: true
format:
  html:
    theme: [cosmo, custom.scss]
    toc: true
    include-in-header: "matomo.html"
    from: markdown+autolink_bare_uris



